on: push
name: Sonar and Tests workflow
jobs:
  sonarCloudTrigger:
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '8'
    - name: SonarCloud Scan
      run: |
        cd api; \
        mvn clean package org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
        -Dsonar.projectKey=oEscal_tqs_project_2 -Dsonar.organization=tqs \
        -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN \
        -Dsonar.qualitygate.wait=true
      env: 
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
