on: push
name: Tests workflow
jobs:
  tests-frontend: 
    runs-on: ubuntu-latest
    name: Selenium tests
    steps:
    - name: Selenoid
      uses: ajinx/selenoid@2.0
    - uses: actions/checkout@v2
    - run: npm ci --prefix code/frontend/web-app
    - name: Run maven and react
      run: | 
        npm start --prefix code/frontend/web-app &; mvn -f api '-Dtest=frontend.webapp.*' 

  tests-backend:
    name: Junit Tests Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Run tests
      run: |
        cd api; mvn test
