on: push
name: Tests backend workflow
jobs:
  tests:
    name: Junit Tests Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Run tests
      run: |
        cd GridBackend; mvn test
