on: push
name: Tests frontend workflow
jobs:
  tests: 
    runs-on: ubuntu-latest
    name: Selenium tests
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Install Google Chrome
      run: |
       chmod +x ./scripts/install_chrome.sh
        ./scripts/install_chrome.sh
    - name: Run react
      run: npm install --prefix GridWebApp; npm start --prefix GridWebApp &
    - name: Run maven selenium tests
      run: mvn -f GridBackend '-Dtest=frontend.webapp.*' test
